### ISSUE TITLE
Using Floating Points in Constraints

### ISSUE THREAD

**Issue by valency007** [sagemath/pplpy#11]
Why can't we use a constraint like x >= 4.5, instead of rewriting it as 2*x >= 9 in the insert() function of Constraint_System() and in the add_constraint() function?

**Comment by videlec** [comment]
The problem is not the `add_constraint` function but the fact that `x >= 4.5` does not work
```
>>> import ppl
>>> x = ppl.Variable(0)
>>> x >= 4.5
x0-4>=0
```
Notice that above we had a silent conversion from `4.5` to `4` which happens when you do `int(4.5)`. This might be considered as a bug as a user might prefer having an explicit `TypeError` here.

The underlying reason is that ppl uses exact arithmetic with arbitrary precision rational numbers (in particular not floating point numbers). The constraints have rational coefficients and chasing denominator allows to restrict to integer coefficients such as `2*x >= 9` .

**Comment by videlec** [comment]
After #17 you get
```python
>>> import ppl
>>> x = ppl.Variable(0)
>>> x >= 4.5
Traceback (most recent call last):
...
TypeError: ppl coefficients must be integral
```
I hope it is less confusing.
